LICENSE

* License as required for the repo!

Create LICENSE for the Repo

---

blog_src/_data/authors.yml
blog_src/_posts/2017-09-11-you-dont-really-know-arduino.md

Emoticons didn't work out well (Alignment issues) and the user description was incorrect.

Post publishing edits to article.

---

README.md
blog_src/_includes/head.html
cas.html
compsoc.html
gyan_src/_includes/head.html
index.html
piston.html
team.html

* SEO Changes made
* Contributing Doc added

Contributing Document added

---

blog_src/_posts/2017-12-21-space-ml.md

Spelling error in space-ml.md

---

data/team.json

Edited the "interests" field of a member in team.json

team.json modified

---

index.html
js/cta.js
res/main.css

Closes #62 
Link for recent blog and gyan articles added on the home page as Call-to-action.

call-to-action for recent articles

---

compsoc.html
data/projects/compsoc.json
index.html
js/sig.js

Closes #130 #131 .
* Project content taken from certificates. Modifications might be needed.
* Research Group brief information hardcoded in `compsoc.html`. 
@salman-bhai @kaushiksk , Please review.

CompSoc content changed + Github Links added

---

data/events.json

#185 
fixed the issue of titles overflowing

Event section titles are fixed

---

publications.html

Aditya A's Paper added

---

index.html
res/main.css

solves 
#211 
Added the faculty advisor in homepage, and adjusted nav height to accompany everyone in page.

Faculty homepage

---

index.html
res/main.css
team.html

I've added SIGHT Chair in the index and team pages, closes #215 
Since the member cards were too big, the new add did not fit in the index page, hence I made the member card smaller to accommodate everyone.

Faculty SIGHT chair add + Member Card edit

---

achieve.html

Closes #214 
Added the 2 new achievements and ordered them chronologically.
Design changes to the site will be made, coming soon :p

Achievements Page Additions

---

index.html
res/main.css

Recruitments message added

---

.gitignore

Added lines in .gitignore file to ignore jekyll cache and metadata.
Closes #254

Added jekyll-cache and jekyll-metadata to .gitignore

---

index.html
joinus.html

Removed recruitment message

---

data/team.json
js/team.js
team.html

had git issue with previous PR
This has the file with fixes.

Team section update

---

achieve.html
data/events.json
data/events/event1.json
data/events/event10.json
data/events/event12.json
data/events/event13.json
data/events/event2.json
data/events/event3.json
data/events/event4.json
data/events/event5.json
data/events/event7.json
data/events/event8.json
data/events/event9.json
index.html

Site event and Achievement Updates

---

blog_src/_posts/2020-03-06-What-is-Machine-Learning.md

minor edits were requested for blog

blog header edits

---

js/header.js
res/css/bootstrap.css
res/css/style.css

Fixed issue with Navbar Dropdown in wrong location

---

data/team.json

Moved batch of 21 to Alumni, updated core positions

Updated team of 2021-22

---

i2c.html

added Results

---

_data/achievements.json
_layouts/home.html

Replaced I2C with Blogs link
New awards added

Achievements update

---

_data/achievements.json
_data/publications.json

awards update

---

robotrix.html

registration button update

---

mystify.html

Overall content modification done

Second update mystify.html

---

_data/publications.json
_layouts/home.html

publication and button update

---

_data/team.json

Remove remaining active members from alumni list

---

impulse.html

Made changes to the Impulse page for the 2024 impulse event

Added 2024 impulse changes

---

CNAME

Remove CNAME record from repo as part of migration to Corpus.

Remove CNAME record
